# Generated by Django 4.2.4 on 2023-12-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_descrip_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
